---
name: Release Binaries on Tag

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release-tag:
    name: Build tag as a release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable]
        TARGET:
          - x86_64-unknown-linux-gnu

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Toolchain setup
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.TARGET }}

      - name: Build
        run: cargo build --release
  
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: --tag ${{ github.ref_name }}
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.git-cliff.outputs.content }}
          tag_name: "${{ github.ref_name }}"
          name: "Release ${{ github.ref_name }}"
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: "${{ secrets.CRATES_TOKEN }}"
        run: cargo publish
