---
name: Release Binaries on Tag

on:
  workflow_dispatch:
    inputs: 

      version:
        description: 'Tag to apply, in the form "v0.0.0"'
        required: true

jobs:
  release-tag:
    name: Build tag as a release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable]
        TARGET:
          - x86_64-unknown-linux-gnu

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Toolchain setup
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu

      - name: Build
        run: cargo build
  
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: --tag ${{ github.event.inputs.version }}
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}
      
      - run: cat CHANGELOG.md

      - name: Upload Release Artifacts
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.md
          tag_name: "${{ github.event.inputs.version }}"
          name: "Release ${{ github.event.inputs.version}}"
          token: "${{ secrets.GITHUB_TOKEN }}"
